#!/sbin/runscript
# Copyright © 2005  TUBITAK/UEKAE
# Licensed under the GNU General Public License, version 2.
# See the file http://www.gnu.org/copyleft/gpl.txt.
#
# Original works belongs to Gentoo Linux

depend() {
	use localmount
}

start() {
	ebegin "Starting syndaemon"
	/usr/bin/syndaemon ${SYNDAEMON_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping syndaemon"
	kill `cat /var/run/syndaemon.pid`
	eend $?
}
