#!/usr/bin/python

import os

hotplugUsermap = "/etc/hotplug/usb/usbcam-gphoto2.usermap"

def postInstall():

    f = open(hotplugUsermap, "w")

    f.write("# !!! DO NOT EDIT THIS FILE !!! This file is automatically generated.\n")
    f.write("# Put your custom entries in /etc/hotplug/usb/usbcam.usermap\n")

    p = os.popen("/usr/lib/libgphoto2/print-usb-usermap", "r")
    f.writelines(p.readlines())

    f.close()
    p.close()

